// Generated by scripts/generate-template-mock-text.mjs — do not edit.

import {mergeMockText, type MockTextDictionary} from './MockTextTranslator';
import common from './common.ar.json';
import t0 from '../ai-chat/AIChatTemplate.ar.json';
import t1 from '../ai-chat-landing/AIChatLandingTemplate.ar.json';
import t2 from '../blank/BlankTemplate.ar.json';
import t3 from '../canvas-editor/CanvasEditorTemplate.ar.json';
import t4 from '../centered-hero/CenteredHeroTemplate.ar.json';
import t5 from '../checkout-wizard/CheckoutWizardTemplate.ar.json';
import t6 from '../classic-gallery/ClassicGalleryTemplate.ar.json';
import t7 from '../contact-form/ContactFormTemplate.ar.json';
import t8 from '../dashboard/DashboardTemplate.ar.json';
import t9 from '../dashboard-alert-rail/DashboardAlertRailTemplate.ar.json';
import t10 from '../dashboard-cohort-funnel/DashboardCohortFunnelTemplate.ar.json';
import t11 from '../dashboard-comparison/DashboardComparisonTemplate.ar.json';
import t12 from '../dashboard-composition/DashboardCompositionTemplate.ar.json';
import t13 from '../dashboard-progress/DashboardProgressTemplate.ar.json';
import t14 from '../dashboard-scorecard/DashboardScorecardTemplate.ar.json';
import t15 from '../detail-page/DetailPageTemplate.ar.json';
import t16 from '../documentation/DocumentationTemplate.ar.json';
import t17 from '../documentation-design/DocumentationDesignTemplate.ar.json';
import t18 from '../documentation-technical/DocumentationTechnicalTemplate.ar.json';
import t19 from '../editor/EditorTemplate.ar.json';
import t20 from '../file-explorer/FileExplorerTemplate.ar.json';
import t21 from '../form-two-column/FormTwoColumnTemplate.ar.json';
import t22 from '../form-wizard/FormWizardTemplate.ar.json';
import t23 from '../form-wizard-dialog/FormWizardDialogTemplate.ar.json';
import t24 from '../form-wizard-inline/FormWizardInlineTemplate.ar.json';
import t25 from '../form-wizard-vertical/FormWizardVerticalTemplate.ar.json';
import t26 from '../gallery-hero/GalleryHeroTemplate.ar.json';
import t27 from '../ide/IDETemplate.ar.json';
import t28 from '../incident-console/IncidentConsoleTemplate.ar.json';
import t29 from '../kanban-board/KanbanBoardTemplate.ar.json';
import t30 from '../library/LibraryTemplate.ar.json';
import t31 from '../login/LoginTemplate.ar.json';
import t32 from '../login-card/LoginCardTemplate.ar.json';
import t33 from '../login-split/LoginSplitTemplate.ar.json';
import t34 from '../login-sso/LoginSSOTemplate.ar.json';
import t35 from '../messaging-shell/MessagingShellTemplate.ar.json';
import t36 from '../mixed-gallery/MixedGalleryTemplate.ar.json';
import t37 from '../payment-form/PaymentFormTemplate.ar.json';
import t38 from '../product-detail/ProductDetailTemplate.ar.json';
import t39 from '../product-gallery/ProductGalleryTemplate.ar.json';
import t40 from '../settings/SettingsTemplate.ar.json';
import t41 from '../settings-dialog/SettingsDialogTemplate.ar.json';
import t42 from '../settings-sidebar/SettingsSidebarTemplate.ar.json';
import t43 from '../shell-nav/ShellNavTemplate.ar.json';
import t44 from '../shell-side-nav/ShellSideNavTemplate.ar.json';
import t45 from '../shell-top-nav/ShellTopNavTemplate.ar.json';
import t46 from '../side-gallery/SideGalleryTemplate.ar.json';
import t47 from '../table/TableTemplate.ar.json';
import t48 from '../table-filter/TableFilterTemplate.ar.json';
import t49 from '../table-grouped/TableGroupedTemplate.ar.json';
import t50 from '../table-inbox/TableInboxTemplate.ar.json';
import t51 from '../table-page/TablePageTemplate.ar.json';
import t52 from '../table-tree/TableTreeTemplate.ar.json';
import t53 from '../theme-showcase/ThemeShowcaseTemplate.ar.json';
import t54 from '../work-item-detail/WorkItemDetailTemplate.ar.json';

/** Arabic vocabulary shared by every template: months, weekdays, quarters, AM/PM. */
export const commonMockTextAr: MockTextDictionary = common;

/** Arabic mock text per template, keyed by template name (e.g. "Dashboard"). */
export const templateMockTextAr: Readonly<Record<string, MockTextDictionary>> = {
  "AIChat": mergeMockText(common, t0),
  "AIChatLanding": mergeMockText(common, t1),
  "Blank": mergeMockText(common, t2),
  "CanvasEditor": mergeMockText(common, t3),
  "CenteredHero": mergeMockText(common, t4),
  "CheckoutWizard": mergeMockText(common, t5),
  "ClassicGallery": mergeMockText(common, t6),
  "ContactForm": mergeMockText(common, t7),
  "Dashboard": mergeMockText(common, t8),
  "DashboardAlertRail": mergeMockText(common, t9),
  "DashboardCohortFunnel": mergeMockText(common, t10),
  "DashboardComparison": mergeMockText(common, t11),
  "DashboardComposition": mergeMockText(common, t12),
  "DashboardProgress": mergeMockText(common, t13),
  "DashboardScorecard": mergeMockText(common, t14),
  "DetailPage": mergeMockText(common, t15),
  "Documentation": mergeMockText(common, t16),
  "DocumentationDesign": mergeMockText(common, t17),
  "DocumentationTechnical": mergeMockText(common, t18),
  "Editor": mergeMockText(common, t19),
  "FileExplorer": mergeMockText(common, t20),
  "FormTwoColumn": mergeMockText(common, t21),
  "FormWizard": mergeMockText(common, t22),
  "FormWizardDialog": mergeMockText(common, t23),
  "FormWizardInline": mergeMockText(common, t24),
  "FormWizardVertical": mergeMockText(common, t25),
  "GalleryHero": mergeMockText(common, t26),
  "IDE": mergeMockText(common, t27),
  "IncidentConsole": mergeMockText(common, t28),
  "KanbanBoard": mergeMockText(common, t29),
  "Library": mergeMockText(common, t30),
  "Login": mergeMockText(common, t31),
  "LoginCard": mergeMockText(common, t32),
  "LoginSplit": mergeMockText(common, t33),
  "LoginSSO": mergeMockText(common, t34),
  "MessagingShell": mergeMockText(common, t35),
  "MixedGallery": mergeMockText(common, t36),
  "PaymentForm": mergeMockText(common, t37),
  "ProductDetail": mergeMockText(common, t38),
  "ProductGallery": mergeMockText(common, t39),
  "Settings": mergeMockText(common, t40),
  "SettingsDialog": mergeMockText(common, t41),
  "SettingsSidebar": mergeMockText(common, t42),
  "ShellNav": mergeMockText(common, t43),
  "ShellSideNav": mergeMockText(common, t44),
  "ShellTopNav": mergeMockText(common, t45),
  "SideGallery": mergeMockText(common, t46),
  "Table": mergeMockText(common, t47),
  "TableFilter": mergeMockText(common, t48),
  "TableGrouped": mergeMockText(common, t49),
  "TableInbox": mergeMockText(common, t50),
  "TablePage": mergeMockText(common, t51),
  "TableTree": mergeMockText(common, t52),
  "ThemeShowcase": mergeMockText(common, t53),
  "WorkItemDetail": mergeMockText(common, t54),
};

/** Arabic mock text per template folder slug (e.g. "dashboard"). */
export const templateMockTextArBySlug: Readonly<Record<string, MockTextDictionary>> = {
  "ai-chat": templateMockTextAr["AIChat"],
  "ai-chat-landing": templateMockTextAr["AIChatLanding"],
  "blank": templateMockTextAr["Blank"],
  "canvas-editor": templateMockTextAr["CanvasEditor"],
  "centered-hero": templateMockTextAr["CenteredHero"],
  "checkout-wizard": templateMockTextAr["CheckoutWizard"],
  "classic-gallery": templateMockTextAr["ClassicGallery"],
  "contact-form": templateMockTextAr["ContactForm"],
  "dashboard": templateMockTextAr["Dashboard"],
  "dashboard-alert-rail": templateMockTextAr["DashboardAlertRail"],
  "dashboard-cohort-funnel": templateMockTextAr["DashboardCohortFunnel"],
  "dashboard-comparison": templateMockTextAr["DashboardComparison"],
  "dashboard-composition": templateMockTextAr["DashboardComposition"],
  "dashboard-progress": templateMockTextAr["DashboardProgress"],
  "dashboard-scorecard": templateMockTextAr["DashboardScorecard"],
  "detail-page": templateMockTextAr["DetailPage"],
  "documentation": templateMockTextAr["Documentation"],
  "documentation-design": templateMockTextAr["DocumentationDesign"],
  "documentation-technical": templateMockTextAr["DocumentationTechnical"],
  "editor": templateMockTextAr["Editor"],
  "file-explorer": templateMockTextAr["FileExplorer"],
  "form-two-column": templateMockTextAr["FormTwoColumn"],
  "form-wizard": templateMockTextAr["FormWizard"],
  "form-wizard-dialog": templateMockTextAr["FormWizardDialog"],
  "form-wizard-inline": templateMockTextAr["FormWizardInline"],
  "form-wizard-vertical": templateMockTextAr["FormWizardVertical"],
  "gallery-hero": templateMockTextAr["GalleryHero"],
  "ide": templateMockTextAr["IDE"],
  "incident-console": templateMockTextAr["IncidentConsole"],
  "kanban-board": templateMockTextAr["KanbanBoard"],
  "library": templateMockTextAr["Library"],
  "login": templateMockTextAr["Login"],
  "login-card": templateMockTextAr["LoginCard"],
  "login-split": templateMockTextAr["LoginSplit"],
  "login-sso": templateMockTextAr["LoginSSO"],
  "messaging-shell": templateMockTextAr["MessagingShell"],
  "mixed-gallery": templateMockTextAr["MixedGallery"],
  "payment-form": templateMockTextAr["PaymentForm"],
  "product-detail": templateMockTextAr["ProductDetail"],
  "product-gallery": templateMockTextAr["ProductGallery"],
  "settings": templateMockTextAr["Settings"],
  "settings-dialog": templateMockTextAr["SettingsDialog"],
  "settings-sidebar": templateMockTextAr["SettingsSidebar"],
  "shell-nav": templateMockTextAr["ShellNav"],
  "shell-side-nav": templateMockTextAr["ShellSideNav"],
  "shell-top-nav": templateMockTextAr["ShellTopNav"],
  "side-gallery": templateMockTextAr["SideGallery"],
  "table": templateMockTextAr["Table"],
  "table-filter": templateMockTextAr["TableFilter"],
  "table-grouped": templateMockTextAr["TableGrouped"],
  "table-inbox": templateMockTextAr["TableInbox"],
  "table-page": templateMockTextAr["TablePage"],
  "table-tree": templateMockTextAr["TableTree"],
  "theme-showcase": templateMockTextAr["ThemeShowcase"],
  "work-item-detail": templateMockTextAr["WorkItemDetail"],
};
