/** @type {import('@solo/docs-types').TemplateDoc} */
export const doc = {
  type: 'page',
  name: 'Service Monitoring Dashboard',
  displayName: 'Service Monitoring Dashboard',
  description:
    'Always-on analytics with a triage rail: status-colored tiles with sparklines, multi-series time charts over a switchable window, and an independently scrolling alert column that folds into the content when narrow.',
  displayNameAr: 'لوحة معلومات مراقبة الخدمات',
  descriptionAr:
    'تحليلات تعمل باستمرار مع شريط للفرز: مربعات ملوّنة بحسب الحالة مع مخططات مصغّرة، ومخططات زمنية متعددة السلاسل على نافذة زمنية قابلة للتبديل، وعمود تنبيهات يُمرَّر باستقلالية وينطوي داخل المحتوى عند ضيق العرض.',
  keywords: [
    'monitoring',
    'uptime',
    'health',
    'latency',
    'alerting',
    'incidents',
    'observability',
    'operations',
    'live status',
    'real-time',
    'reliability',
    'traffic',
    'anomalies',
    'severity',
    'on-call',
    'oncall',
    'fleet',
    'pipelines',
    'freshness',
    'command center',
  ],
  isReady: true,
  category: 'Dashboard - Monitoring',
  order: 6,
  filter: 'Dashboard',
  previewAspectRatio: 16 / 10,
  slug: 'dashboard-alert-rail',
};
