// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import AIChatTemplate from '@solo/templates/ai-chat/AIChatTemplate';

const meta: Meta<typeof AIChatTemplate> = {
  title: 'Templates/38 AI Chat Conversation',
  component: AIChatTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Transcript of alternating turns carrying mixed rich content inline (markdown, code blocks, collapsible tool-call output) beside a resizable artifact panel that holds generated output while the stream keeps scrolling."}},
  },
};

export default meta;

export const Template: StoryObj<typeof AIChatTemplate> = {
  name: "AI Chat Conversation",
};
