// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import AIChatLandingTemplate from '@solo/templates/ai-chat-landing/AIChatLandingTemplate';

const meta: Meta<typeof AIChatLandingTemplate> = {
  title: 'Templates/39 AI Chat Landing',
  component: AIChatLandingTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Zero-state entry surface centered on a single composer with suggestion chips instead of history, sized for the moment before any content exists. The empty counterpart to a transcript."}},
  },
};

export default meta;

export const Template: StoryObj<typeof AIChatLandingTemplate> = {
  name: "AI Chat Landing",
};
