// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import BlankTemplate from '@solo/templates/blank/BlankTemplate';

const meta: Meta<typeof BlankTemplate> = {
  title: 'Templates/46 Blank',
  component: BlankTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Bare scaffold: one heading slot, one empty content region, no navigation and no chrome. The starting point when every other layout imposes more structure than wanted."}},
  },
};

export default meta;

export const Template: StoryObj<typeof BlankTemplate> = {
  name: "Blank",
};
