// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import CenteredHeroTemplate from '@solo/templates/centered-hero/CenteredHeroTemplate';

const meta: Meta<typeof CenteredHeroTemplate> = {
  title: 'Templates/40 Centered Hero',
  component: CenteredHeroTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Symmetrical centered stack (headline, short blurb, paired call-to-action buttons) resting on one wide full-bleed picture, with nothing on either flank competing."}},
  },
};

export default meta;

export const Template: StoryObj<typeof CenteredHeroTemplate> = {
  name: "Centered Hero",
};
