// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import CheckoutWizardTemplate from '@solo/templates/checkout-wizard/CheckoutWizardTemplate';

const meta: Meta<typeof CheckoutWizardTemplate> = {
  title: 'Templates/13 Checkout Wizard',
  component: CheckoutWizardTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Multi-step checkout, cart, order, and payment wizard with a running summary that recalculates as answers change. It adapts to its host width, renders the summary first on narrow surfaces, validates every forward path, and completes locally without sending payment."}},
  },
};

export default meta;

export const Template: StoryObj<typeof CheckoutWizardTemplate> = {
  name: "Checkout Wizard",
};
