// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import ClassicGalleryTemplate from '@solo/templates/classic-gallery/ClassicGalleryTemplate';

const meta: Meta<typeof ClassicGalleryTemplate> = {
  title: 'Templates/41 Classic Gallery',
  component: ClassicGalleryTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Uniform grid of equal-ratio media tiles under a centered intro, with filter tabs that narrow the set in place. Regular rhythm, unlike the variable-height masonry variant."}},
  },
};

export default meta;

export const Template: StoryObj<typeof ClassicGalleryTemplate> = {
  name: "Classic Gallery",
};
