// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import ContactFormTemplate from '@solo/templates/contact-form/ContactFormTemplate';

const meta: Meta<typeof ContactFormTemplate> = {
  title: 'Templates/14 Contact Form',
  component: ContactFormTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Flat single-column form mixing control types (text, pill toggles, dropdowns, long free-text) landing on one full-width submit. No steps, no branching, no summary rail."}},
  },
};

export default meta;

export const Template: StoryObj<typeof ContactFormTemplate> = {
  name: "Contact Form",
};
