// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DashboardProgressTemplate from '@solo/templates/dashboard-progress/DashboardProgressTemplate';

const meta: Meta<typeof DashboardProgressTemplate> = {
  title: 'Templates/05 Project Status Dashboard',
  component: DashboardProgressTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Status analytics mixing progress and time-axis shapes: a completion donut, a horizontal timeline of dated bars against a today marker, a per-owner table with progress and status, an at-risk list, and a burndown."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DashboardProgressTemplate> = {
  name: "Project Status Dashboard",
};
