// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DashboardScorecardTemplate from '@solo/templates/dashboard-scorecard/DashboardScorecardTemplate';

const meta: Meta<typeof DashboardScorecardTemplate> = {
  title: 'Templates/02 Executive Summary Dashboard',
  component: DashboardScorecardTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Report-shaped analytics with a prose rail beside the charts: a scorecard of headline numbers with period deltas and status coloring, goal-attainment bars, a trend grid, and a written commentary column that folds beneath the content when narrow."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DashboardScorecardTemplate> = {
  name: "Executive Summary Dashboard",
};
