// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DashboardComparisonTemplate from '@solo/templates/dashboard-comparison/DashboardComparisonTemplate';

const meta: Meta<typeof DashboardComparisonTemplate> = {
  title: 'Templates/01 Data Dashboard',
  component: DashboardComparisonTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Comparison-heavy analytics behind a persistent filter bar: tiles that each carry an inline sparkline and several period-over-period deltas, then segmented breakdowns underneath. Every number is shown against another number."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DashboardComparisonTemplate> = {
  name: "Data Dashboard",
};
