// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DashboardTemplate from '@solo/templates/dashboard/DashboardTemplate';

const meta: Meta<typeof DashboardTemplate> = {
  title: 'Templates/00 Analytics Dashboard',
  component: DashboardTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Three-band analytics: a row of headline tiles, then charts, then supporting tables, all re-reading from one global filter bar. Breadth over depth, a summary surface rather than a drill-down."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DashboardTemplate> = {
  name: "Analytics Dashboard",
};
