// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DashboardCohortFunnelTemplate from '@solo/templates/dashboard-cohort-funnel/DashboardCohortFunnelTemplate';

const meta: Meta<typeof DashboardCohortFunnelTemplate> = {
  title: 'Templates/03 Funnel & Cohort Dashboard',
  component: DashboardCohortFunnelTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Analytics for sequence and retention questions, pairing two shapes a plain dashboard cannot hold: a staged funnel where each step reads as drop-off against the one before, and a two-axis cohort matrix rendered as a heatmap."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DashboardCohortFunnelTemplate> = {
  name: "Funnel & Cohort Dashboard",
};
