// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DashboardCompositionTemplate from '@solo/templates/dashboard-composition/DashboardCompositionTemplate';

const meta: Meta<typeof DashboardCompositionTemplate> = {
  title: 'Templates/04 Portfolio Dashboard',
  component: DashboardCompositionTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Analytics for a value-over-time question: balance and change tiles above a stacked area chart of composition through time, closing on a ranked table of the largest contributors."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DashboardCompositionTemplate> = {
  name: "Portfolio Dashboard",
};
