// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DashboardAlertRailTemplate from '@solo/templates/dashboard-alert-rail/DashboardAlertRailTemplate';

const meta: Meta<typeof DashboardAlertRailTemplate> = {
  title: 'Templates/06 Service Monitoring Dashboard',
  component: DashboardAlertRailTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Always-on analytics with a triage rail: status-colored tiles with sparklines, multi-series time charts over a switchable window, and an independently scrolling alert column that folds into the content when narrow."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DashboardAlertRailTemplate> = {
  name: "Service Monitoring Dashboard",
};
