// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DetailPageTemplate from '@solo/templates/detail-page/DetailPageTemplate';

const meta: Meta<typeof DetailPageTemplate> = {
  title: 'Templates/35 Order Detail',
  component: DetailPageTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Single-record detail in two columns: a summary header with status and actions, a repeating line-item list, a totals block that sums it, and a chronological activity timeline in the rail. The shape for any record holding children plus a history: a customer order with shipping, an invoice, a transaction, or a job."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DetailPageTemplate> = {
  name: "Order Detail",
};
