// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DocumentationTemplate from '@solo/templates/documentation/DocumentationTemplate';

const meta: Meta<typeof DocumentationTemplate> = {
  title: 'Templates/32 Documentation Catalog',
  component: DocumentationTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Reference landing that is pure wayfinding: a banner above a grid of category cards linking into sections, with no article content on the surface itself."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DocumentationTemplate> = {
  name: "Documentation Catalog",
};
