// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DocumentationDesignTemplate from '@solo/templates/documentation-design/DocumentationDesignTemplate';

const meta: Meta<typeof DocumentationDesignTemplate> = {
  title: 'Templates/33 Documentation Design',
  component: DocumentationDesignTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Reference article alternating prose with live rendered examples: an interactive preview, a property table, paired do and don't comparisons, and copyable code blocks."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DocumentationDesignTemplate> = {
  name: "Documentation Design",
};
