// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import DocumentationTechnicalTemplate from '@solo/templates/documentation-technical/DocumentationTechnicalTemplate';

const meta: Meta<typeof DocumentationTechnicalTemplate> = {
  title: 'Templates/34 Documentation Technical',
  component: DocumentationTechnicalTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Reference article ordered as sequential numbered steps with code at each stage, plus callout cards for prerequisites and onward links. A linear walkthrough rather than a browsable reference."}},
  },
};

export default meta;

export const Template: StoryObj<typeof DocumentationTechnicalTemplate> = {
  name: "Documentation Technical",
};
