// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import EditorTemplate from '@solo/templates/editor/EditorTemplate';

const meta: Meta<typeof EditorTemplate> = {
  title: 'Templates/30 Page Editor',
  component: EditorTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Three-pane authoring workspace: a source palette on one flank, a live canvas in the middle, and an inspector that retargets to whatever is selected. Drag and drop to reorder, edit to see it render immediately."}},
  },
};

export default meta;

export const Template: StoryObj<typeof EditorTemplate> = {
  name: "Page Editor",
};
