// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import FileExplorerTemplate from '@solo/templates/file-explorer/FileExplorerTemplate';

const meta: Meta<typeof FileExplorerTemplate> = {
  title: 'Templates/27 File Explorer',
  component: FileExplorerTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Hierarchical browser that drills through nested levels as adjacent columns rather than replacing the list each time, with breadcrumb history, switchable list and grid density, and a metadata pane for the selected node."}},
  },
};

export default meta;

export const Template: StoryObj<typeof FileExplorerTemplate> = {
  name: "File Explorer",
};
