// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import FormWizardVerticalTemplate from '@solo/templates/form-wizard-vertical/FormWizardVerticalTemplate';

const meta: Meta<typeof FormWizardVerticalTemplate> = {
  title: 'Templates/19 Vertical Wizard',
  component: FormWizardVerticalTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Multi-step wizard with the steps in a fixed left rail that stays visible while the form scrolls, plus a side panel whose guidance follows the focused field. Suits long or unequal steps carrying uploads, previews, and dense review metadata. As width tightens the guidance drops first, then the rail rotates into a horizontal stepper above the form."}},
  },
};

export default meta;

export const Template: StoryObj<typeof FormWizardVerticalTemplate> = {
  name: "Vertical Wizard",
};
