// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import FormWizardInlineTemplate from '@solo/templates/form-wizard-inline/FormWizardInlineTemplate';

const meta: Meta<typeof FormWizardInlineTemplate> = {
  title: 'Templates/17 Inline Wizard',
  component: FormWizardInlineTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Accordion wizard stacking every step in one column: the active step expands in place while finished ones collapse to a single line carrying their result and a way back in. Steps that run themselves expand into a nested stepper that ticks check by check and halts the column where one fails. Best when later steps depend on what earlier ones decided."}},
  },
};

export default meta;

export const Template: StoryObj<typeof FormWizardInlineTemplate> = {
  name: "Inline Wizard",
};
