// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import FormWizardTemplate from '@solo/templates/form-wizard/FormWizardTemplate';

const meta: Meta<typeof FormWizardTemplate> = {
  title: 'Templates/16 Form Wizard',
  component: FormWizardTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Linear multi-step form that moves through one panel at a time, with a horizontal progress track pinned above rather than running down a rail, so every step keeps the full content width for its fields. Only the current step renders, unlike an accordion where each section expands into one long scrolling form. Each advance is validated, and a step left broken stays flagged to jump back to."}},
  },
};

export default meta;

export const Template: StoryObj<typeof FormWizardTemplate> = {
  name: "Form Wizard",
};
