// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import FormTwoColumnTemplate from '@solo/templates/form-two-column/FormTwoColumnTemplate';

const meta: Meta<typeof FormTwoColumnTemplate> = {
  title: 'Templates/18 Two-column Form',
  component: FormTwoColumnTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Form split into two columns beneath a hero header: inputs on one flank, a persistent context panel opposite that stays put while the fields scroll. Flat, single submit, no steps."}},
  },
};

export default meta;

export const Template: StoryObj<typeof FormTwoColumnTemplate> = {
  name: "Two-column Form",
};
