// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import FormWizardDialogTemplate from '@solo/templates/form-wizard-dialog/FormWizardDialogTemplate';

const meta: Meta<typeof FormWizardDialogTemplate> = {
  title: 'Templates/15 Dialog Wizard',
  component: FormWizardDialogTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Step through a short flow in a dialog, overlay, or popup launched from the page underneath, which stays where it was. Compact step markers and a pinned action row inside a constrained width, rather than the full page a wizard usually gets. Best for two to four short steps — setup, invite, schedule, onboarding — where losing the context underneath would cost more than the flow is worth."}},
  },
};

export default meta;

export const Template: StoryObj<typeof FormWizardDialogTemplate> = {
  name: "Dialog Wizard",
};
