// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import GalleryHeroTemplate from '@solo/templates/gallery-hero/GalleryHeroTemplate';

const meta: Meta<typeof GalleryHeroTemplate> = {
  title: 'Templates/42 Gallery Hero',
  component: GalleryHeroTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Centered stack (headline, short blurb, call-to-action buttons) resolving into a multi-image photo grid rather than one wide full-bleed picture, so the imagery reads as a set."}},
  },
};

export default meta;

export const Template: StoryObj<typeof GalleryHeroTemplate> = {
  name: "Gallery Hero",
};
