// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import IDETemplate from '@solo/templates/ide/IDETemplate';

const meta: Meta<typeof IDETemplate> = {
  title: 'Templates/28 IDE',
  component: IDETemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Dense multi-pane workspace of resizable, collapsible regions: a hierarchy tree on one flank, tabbed documents in the middle, a docked drawer along the bottom, an inspector opposite. Drag a divider to resize or collapse any of them."}},
  },
};

export default meta;

export const Template: StoryObj<typeof IDETemplate> = {
  name: "IDE",
};
