// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import IncidentConsoleTemplate from '@solo/templates/incident-console/IncidentConsoleTemplate';

const meta: Meta<typeof IncidentConsoleTemplate> = {
  title: 'Templates/52 Incident Console',
  component: IncidentConsoleTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Dense row queue with an inspector: severity-coded rows grouped by status, a saved-search filter bar, a segmented status control, and a resizable detail pane for the selected row. Rows, not cards, sized for scanning volume."}},
  },
};

export default meta;

export const Template: StoryObj<typeof IncidentConsoleTemplate> = {
  name: "Incident Console",
};
