// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import KanbanBoardTemplate from '@solo/templates/kanban-board/KanbanBoardTemplate';

const meta: Meta<typeof KanbanBoardTemplate> = {
  title: 'Templates/29 Kanban Board',
  component: KanbanBoardTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Horizontal lanes of draggable cards where the column itself is the status, so drag and drop between lanes is the state change. Fixed columns, variable-height cards."}},
  },
};

export default meta;

export const Template: StoryObj<typeof KanbanBoardTemplate> = {
  name: "Kanban Board",
};
