// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import LibraryTemplate from '@solo/templates/library/LibraryTemplate';

const meta: Meta<typeof LibraryTemplate> = {
  title: 'Templates/31 Card Grid',
  component: LibraryTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Searchable, browsable card grid with filter tabs and a real empty state: uniform tiles organized by topic, narrowing in place, with no detail surface behind them."}},
  },
};

export default meta;

export const Template: StoryObj<typeof LibraryTemplate> = {
  name: "Card Grid",
};
