// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import LoginSplitTemplate from '@solo/templates/login-split/LoginSplitTemplate';

const meta: Meta<typeof LoginSplitTemplate> = {
  title: 'Templates/24 Login Split',
  component: LoginSplitTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Credential form filling one half of a two-pane split, full-bleed media holding the other. Same fields as the card variant, but the layout carries brand imagery."}},
  },
};

export default meta;

export const Template: StoryObj<typeof LoginSplitTemplate> = {
  name: "Login Split",
};
