// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import LoginSSOTemplate from '@solo/templates/login-sso/LoginSSOTemplate';

const meta: Meta<typeof LoginSSOTemplate> = {
  title: 'Templates/25 Login SSO',
  component: LoginSSOTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Progressive credential flow that branches on input: the email domain resolves an identity provider and redirects, with a password path as fallback. Two-stage rather than one form."}},
  },
};

export default meta;

export const Template: StoryObj<typeof LoginSSOTemplate> = {
  name: "Login SSO",
};
