// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import LoginCardTemplate from '@solo/templates/login-card/LoginCardTemplate';

const meta: Meta<typeof LoginCardTemplate> = {
  title: 'Templates/23 Login Card',
  component: LoginCardTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Credential form inside an elevated centered card, third-party provider buttons separated from the fields by a divider, secondary sign-up and legal links beneath."}},
  },
};

export default meta;

export const Template: StoryObj<typeof LoginCardTemplate> = {
  name: "Login Card",
};
