// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import LoginTemplate from '@solo/templates/login/LoginTemplate';

const meta: Meta<typeof LoginTemplate> = {
  title: 'Templates/51 Basic Login',
  component: LoginTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Minimal centered credential form on a plain ground: two fields and a submit, nothing competing for attention. The least-chrome entry surface."}},
  },
};

export default meta;

export const Template: StoryObj<typeof LoginTemplate> = {
  name: "Basic Login",
};
