// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import MessagingShellTemplate from '@solo/templates/messaging-shell/MessagingShellTemplate';

const meta: Meta<typeof MessagingShellTemplate> = {
  title: 'Templates/53 Messaging Shell',
  component: MessagingShellTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Four-column nested navigation narrowing left to right (team workspace, channel list, message stream, thread panel) where each column scopes the next. Dense rows, zero cards."}},
  },
};

export default meta;

export const Template: StoryObj<typeof MessagingShellTemplate> = {
  name: "Messaging Shell",
};
