// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import MixedGalleryTemplate from '@solo/templates/mixed-gallery/MixedGalleryTemplate';

const meta: Meta<typeof MixedGalleryTemplate> = {
  title: 'Templates/43 Mixed Gallery',
  component: MixedGalleryTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Masonry grid of variable-height tiles that pack against each other instead of cropping to a shared ratio, captioned per tile. Irregular rhythm, unlike the uniform gallery."}},
  },
};

export default meta;

export const Template: StoryObj<typeof MixedGalleryTemplate> = {
  name: "Mixed Gallery",
};
