// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import PaymentFormTemplate from '@solo/templates/payment-form/PaymentFormTemplate';

const meta: Meta<typeof PaymentFormTemplate> = {
  title: 'Templates/12 Checkout Form',
  component: PaymentFormTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Long sectioned form running beside a summary that stays visible while the fields scroll and recalculates as they change, ending on a terminal confirm of the total. Sections run contact, address, delivery choice, then card details."}},
  },
};

export default meta;

export const Template: StoryObj<typeof PaymentFormTemplate> = {
  name: "Checkout Form",
};
