// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import ProductDetailTemplate from '@solo/templates/product-detail/ProductDetailTemplate';

const meta: Meta<typeof ProductDetailTemplate> = {
  title: 'Templates/36 Product Detail',
  component: ProductDetailTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Single-item detail pairing a media gallery with a selection column: variant swatches, a quantity stepper, primary and secondary commit actions, and collapsible specification sections below."}},
  },
};

export default meta;

export const Template: StoryObj<typeof ProductDetailTemplate> = {
  name: "Product Detail",
};
