// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import ProductGalleryTemplate from '@solo/templates/product-gallery/ProductGalleryTemplate';

const meta: Meta<typeof ProductGalleryTemplate> = {
  title: 'Templates/44 Product Gallery',
  component: ProductGalleryTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Uniform card grid where every tile carries media, title, supporting line, and a price. Browse-to-select only, with no filtering and no detail surface."}},
  },
};

export default meta;

export const Template: StoryObj<typeof ProductGalleryTemplate> = {
  name: "Product Gallery",
};
