// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import SettingsDialogTemplate from '@solo/templates/settings-dialog/SettingsDialogTemplate';

const meta: Meta<typeof SettingsDialogTemplate> = {
  title: 'Templates/20 Settings Dialog',
  component: SettingsDialogTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Preferences inside a modal container with searchable section navigation, so configuration happens without leaving whatever is underneath. Grouped toggles, live preview of appearance choices, rebindable shortcuts."}},
  },
};

export default meta;

export const Template: StoryObj<typeof SettingsDialogTemplate> = {
  name: "Settings Dialog",
};
