// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import SettingsTemplate from '@solo/templates/settings/SettingsTemplate';

const meta: Meta<typeof SettingsTemplate> = {
  title: 'Templates/21 Settings Form',
  component: SettingsTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Preferences as one continuously scrolling form, sections stacked in order with no navigation between them. The simplest settings shape: everything reachable by scrolling."}},
  },
};

export default meta;

export const Template: StoryObj<typeof SettingsTemplate> = {
  name: "Settings Form",
};
