// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import SettingsSidebarTemplate from '@solo/templates/settings-sidebar/SettingsSidebarTemplate';

const meta: Meta<typeof SettingsSidebarTemplate> = {
  title: 'Templates/22 Settings Panels',
  component: SettingsSidebarTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Preferences split into nav-switched panels: a persistent section list swaps the pane beside it, and rows edit in place rather than opening a separate form."}},
  },
};

export default meta;

export const Template: StoryObj<typeof SettingsSidebarTemplate> = {
  name: "Settings Panels",
};
