// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import ShellTopNavTemplate from '@solo/templates/shell-top-nav/ShellTopNavTemplate';

const meta: Meta<typeof ShellTopNavTemplate> = {
  title: 'Templates/49 Top Nav',
  component: ShellTopNavTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Application frame with horizontal navigation only: a centered bar whose items open full-width mega-menu panels, over placeholder content that keeps the entire width."}},
  },
};

export default meta;

export const Template: StoryObj<typeof ShellTopNavTemplate> = {
  name: "Top Nav",
};
