// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import ShellSideNavTemplate from '@solo/templates/shell-side-nav/ShellSideNavTemplate';

const meta: Meta<typeof ShellSideNavTemplate> = {
  title: 'Templates/48 Side Nav',
  component: ShellSideNavTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Application frame with a single collapsible, resizable left rail carrying grouped history and search, wrapping the main content. Vertical navigation only, no top bar."}},
  },
};

export default meta;

export const Template: StoryObj<typeof ShellSideNavTemplate> = {
  name: "Side Nav",
};
