// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import ShellNavTemplate from '@solo/templates/shell-nav/ShellNavTemplate';

const meta: Meta<typeof ShellNavTemplate> = {
  title: 'Templates/47 Shell Nav',
  component: ShellNavTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Application frame combining both navigation axes: a top menu bar with command-palette search over a resizable hierarchy rail, wrapping placeholder content. For when one axis is not enough."}},
  },
};

export default meta;

export const Template: StoryObj<typeof ShellNavTemplate> = {
  name: "Shell Nav",
};
