// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import SideGalleryTemplate from '@solo/templates/side-gallery/SideGalleryTemplate';

const meta: Meta<typeof SideGalleryTemplate> = {
  title: 'Templates/45 Side Gallery',
  component: SideGalleryTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Asymmetric split section: a copy column of headline, supporting text, and links held against a clustered image collage opposite. Deliberately off-balance, unlike the centered hero."}},
  },
};

export default meta;

export const Template: StoryObj<typeof SideGalleryTemplate> = {
  name: "Side Gallery",
};
