// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import TableFilterTemplate from '@solo/templates/table-filter/TableFilterTemplate';

const meta: Meta<typeof TableFilterTemplate> = {
  title: 'Templates/07 Filterable Table',
  component: TableFilterTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Flat row collection built around progressive filtering: a token bar that escalates into full query syntax, saved views that persist a filter set, column and grouping options, and a resizable detail pane."}},
  },
};

export default meta;

export const Template: StoryObj<typeof TableFilterTemplate> = {
  name: "Filterable Table",
};
