// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import TableTreeTemplate from '@solo/templates/table-tree/TableTreeTemplate';

const meta: Meta<typeof TableTreeTemplate> = {
  title: 'Templates/11 Tree Table',
  component: TableTreeTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Hierarchical table where every parent row rolls up from its children — a code repository whose folders show the newest commit beneath them, beside a detail sidebar and a rendered README. Columns resize, siblings sort within their own level, arrow keys walk the rows, and search prunes the tree to matching branches."}},
  },
};

export default meta;

export const Template: StoryObj<typeof TableTreeTemplate> = {
  name: "Tree Table",
};
