// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import TablePageTemplate from '@solo/templates/table-page/TablePageTemplate';

const meta: Meta<typeof TablePageTemplate> = {
  title: 'Templates/10 Searchable Table',
  component: TablePageTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Flat table of uniform rows under a block of record-level facts, narrowed three ways at once — a full-text search box, a scope toggle, and per-column popovers — with sortable and filterable columns, per-row hover detail, and totals derived from the visible rows that flag themselves as partial while a filter is on. The shape for one homogeneous list, not nested rows or groups with their own columns."}},
  },
};

export default meta;

export const Template: StoryObj<typeof TablePageTemplate> = {
  name: "Searchable Table",
};
