// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import TableGroupedTemplate from '@solo/templates/table-grouped/TableGroupedTemplate';

const meta: Meta<typeof TableGroupedTemplate> = {
  title: 'Templates/08 Grouped Table',
  component: TableGroupedTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Row collection bundled into collapsible sections with per-group counts, so a long list reads as a handful of blocks that expand and collapse. Query filtering and a resizable inspector for the selected row."}},
  },
};

export default meta;

export const Template: StoryObj<typeof TableGroupedTemplate> = {
  name: "Grouped Table",
};
