// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import TableInboxTemplate from '@solo/templates/table-inbox/TableInboxTemplate';

const meta: Meta<typeof TableInboxTemplate> = {
  title: 'Templates/09 Inbox Table',
  component: TableInboxTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Two-pane message queue: the table indexes a reading pane rather than being the destination, with a divider you drag to resize. Rows stack when the table narrows, not the window; threads read as collapsible messages; replying opens a composer that leaves the list live."}},
  },
};

export default meta;

export const Template: StoryObj<typeof TableInboxTemplate> = {
  name: "Inbox Table",
};
