// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import TableTemplate from '@solo/templates/table/TableTemplate';

const meta: Meta<typeof TableTemplate> = {
  title: 'Templates/50 Simple Table',
  component: TableTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Flat row collection where columns sort, rows select into a bulk-action toolbar, and each row carries an overflow menu. Sortable but ungrouped, with no detail pane, the baseline shape."}},
  },
};

export default meta;

export const Template: StoryObj<typeof TableTemplate> = {
  name: "Simple Table",
};
