// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import ThemeShowcaseTemplate from '@solo/templates/theme-showcase/ThemeShowcaseTemplate';

const meta: Meta<typeof ThemeShowcaseTemplate> = {
  title: 'Templates/54 Theme Showcase',
  component: ThemeShowcaseTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Several unrelated product surfaces rendered together on one canvas so a token change can be judged across contexts at once. A comparison harness rather than a layout to ship."}},
  },
};

export default meta;

export const Template: StoryObj<typeof ThemeShowcaseTemplate> = {
  name: "Theme Showcase",
};
