// Generated by scripts/generate-template-stories.mjs — do not edit.

import type {Meta, StoryObj} from '@storybook/react';
import WorkItemDetailTemplate from '@solo/templates/work-item-detail/WorkItemDetailTemplate';

const meta: Meta<typeof WorkItemDetailTemplate> = {
  title: 'Templates/37 Work Item Detail',
  component: WorkItemDetailTemplate,
  parameters: {
    layout: 'fullscreen',
    solo: {bare: true},
    docs: {description: {component: "Single work-item detail in two columns: a title with a status selector, a description, a subtask checklist with progress, an attachments block, and a comment and activity feed in the main column, plus a property rail with assignee, dates, labels, and linked items. The shape for any tracked item with children, properties, and a comment history — a task, ticket, issue, story, bug, card, request, or work item."}},
  },
};

export default meta;

export const Template: StoryObj<typeof WorkItemDetailTemplate> = {
  name: "Work Item Detail",
};
